## _Обработка ошибок_

```
try {
  console.log(undefVar);
} catch (error) {
  console.log(error.name);     /=/ Выводит имя ошибки
                                  (в данном случае "ReferenceError")
  console.log(error.message);  /=/ Выводит сообщение об ошибке
																  (в данном случае "undefVar is not defined")
  console.log(error.stack);    /=/ Выводит стек вызовов.
																  Содержит информацию о месте, где произошла ошибка.
}
```
#стек_вызовов

### _Проброс исключений_

Для его реализации нам достаточно проверить во внутреннем блоке `catch` тип ошибки и, если она не соответствует `Error`, то передать дальше:

```
// let res = 0;
try {
  res = divide(1, 2);
  console.log(res);
} catch (error) {
  if (error.name == "Error") {
    console.log(error.name);
    console.log(error.message);
  } else {
    throw error; /=/ Проброс ошибки наверх
  }
}
```

Соответственно, внутри будет обрабатывать только исключения `Error`, а остальные пробрасывать блокам более высокого уровня.

```
try {
    return getData(key);
} catch (error) {
    if (error instanceof NotFoundError) {
      throw error; /=/ Проброс ошибки наверх
    }
}
```

#проброс*ошибки*наверх

### _Создание пользовательских Errors_

В этом примере, если функция `getData` вызывает ошибку `NotFoundError`, она будет выброшена с помощью оператора `throw` и поймана в блоке `try-catch` внутри функции `process`.
Затем можно обработать исключение `NotFoundError` в блоке `catch` с помощью условного оператора `if`.

```
function getData() {
  // Логика получения данных
  if (условие) {
    throw new NotFoundError("Данные не найдены");
  }
}

function process() {
  try {
    getData();
  } catch (error) {
    if (error instanceof NotFoundError) { /=/ true
      // Обработка исключения NotFoundError
    } else {
      // Обработка других исключений
    }
  }
}
process()
```
#обработка_исключений

```
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = "ValidationError";
  }
}

// Использование

function readUser(json) {
  let user = JSON.parse(json);

  if (!user.age) {
    throw new ValidationError("Нет поля: age");
  }
  if (!user.name) {
    throw new ValidationError("Нет поля: name");
  }
  return user;
}

// Рабочий пример с try..catch

try {
  let user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof ValidationError) {
    alert("Некорректные данные: " + err.message);
    // Некорректные данные: Нет поля: name
  } else if (err instanceof SyntaxError) {
    alert("JSON Ошибка Синтаксиса: " + err.message);
  } else {
    throw err;
    // Неизвестная ошибка, пробросить исключение
  }
}
```

## _Асинхронность_

Если вы хотите получить `значение`, возвращаемое после определенного `времени`, вы можете использовать `промисы` или `асинхронные функции`.

```
let fileSizes = {
  testFile1: 65,
  testFile2: 48
};

function getFileSize(filename, cb) {
  setTimeout(() => cb(fileSizes[filename]), Math.random() * 500);
}

async function sumFileSizes(filename1, filename2, cb) {
  try {
    const size1 = await new Promise((resolve) => {
      getFileSize(filename1, resolve);
    });
    const size2 = await new Promise((resolve) => {
      getFileSize(filename2, resolve);
    });

    return cb(size1 + size2);
  } catch (error) {
    console.log(error);
  }
}

sumFileSizes("testFile1", "testFile2", (sum) => {
  return sum; /=/ 113
});
```

### _Callback_

![[callback]]

---
Переписывание асинхронного `коллбэка` в приемлемый вид

```
async function pageLoader(callback) {
  const data = await fetch("https://jsonplaceholder.typicode.com/todos/1");
  callback(data);
}

function pageLoader(callback) {
  fetch("https://jsonplaceholder.typicode.com/todos/1")
    .then((response) => response.json())
    .then((data) => callback(data))
    .catch((error) => console.error(error));
}

async function pageLoader(callback) {
  try {
    const response = await fetch("https://jsonplaceholder.typicode.com/todos/1");
    const json = await response.json();
    callback(json);
  } catch (error) {
    console.error(error);
  }
}

function getAjax(data) {
  console.log("Запрос послан");
  console.log("Ответ сервера");
  console.log(data);
}

pageLoader(getAjax);
```

### _Promise_

![[promises]]

### _Async/await_

- Функция которая является `async`( `асинхронной`) - всегда возвращает `return promise`
Тк внутри все работает на промисах и колбэках.

```
async function fetchAsyncTodos() {  
  console.log("Fetch todo started...");  
  await delay(2000); /=/ (**)
  const response = await fetch(url);  
  const data = await response.json();  
  console.log("Data:", data);  
}
```

`** await` - позволяет не переходить к следующей сточке, пока `promise` на текущей строчки не выполнится

## _Асинхронные циклы_

```
async function processArray(array) {
  array.forEach(item => {
    // тут мы определили синхронную анонимную функцию
    // НО ЭТО КОД ВЫДАСТ ОШИБКУ!
    await func(item);
  })
}
```

Этот код выдаст ошибку. Почему? Потому что мы не можем использовать `await` внутри синхронной функции. Как вы можете видеть `processArray` — это асинхронная функция. Но анонимная функция, которую мы используем для `forEach`, является **синхронной**.

### _Способы решения_

### _Обработка цикла последовательно_

- Позволяет дождаться выполнения функции `delayedLog(item)` и ее завершения, прежде чем перейти к следующей итерации цикла.

```
async function processArray(array) {
  for (const item of array) {
    await delayedLog(item);
  }
  console.log('Done!');
}
```

```
async function increaseSalary() {  
  const increasedWorkers = [];  
  
  try {  
    const workers = await api.getEmployees();  
    const salaryAvg =  
      workers.reduce((acc, el) => acc + el.salary, 0) / workers.length;  
  
    for (let { id, name, salary } of workers) {  
      try {  
        const newSalary = salary < salaryAvg ? salary * 1.2 : salary * 1.1;  
        const increased = await api.setEmployeeSalary(id, newSalary);  
  
        await api.notifyEmployee(id, `${name}, your new salary is ${newSalary}!`);  
        increasedWorkers.push(increased);  
      } catch (error) {  
        await api.notifyAdmin(error);  
      }  
    }  
    
  } catch (error) {  
    api.notifyAdmin(error);  
  } finally {  
    const increasedSum = increasedWorkers.reduce((acc, el) => {  
      return acc + el.salary;  
    }, 0);  
    api.sendBudgetToAccounting(increasedSum);  
    return increasedWorkers.length;  
  }  
}
```
 
### _Обработка цикла параллельно_

Такой подход может запустить несколько `delayLog` задач параллельно. Но будьте аккуратны с большими массивами. Слишком много задач может быть слишком тяжело для CPU и памяти.

```
async function processArray(array) {
  const promises = array.map(delayedLog); /=/ Создаем массив промисов
  await Promise.all(promises); /=/ Ждем когда всё промисы будут выполнены
  console.log('Done!');
}
```
---

**-> C использованием `await`** *(последовательно)*
```
async function processArray(array) {
  await Promise.all(array.map(async (item) => await func(item))); /=/ (*)
  console.log('Done!');
}
```

`* await` перед вызовом `func(item)` - код будет ждать, пока каждый вызов `func(item)` завершится, прежде чем перейти к следующей итерации цикла `map`.

**-> Без использования `await`** *(параллельно)*
```
async function processArray(array) {
  await Promise.all(array.map((item) => func(item)));
  console.log('Done!');
}
```

Во втором варианте, где не используется `await` перед вызовом `func(item)`, каждый вызов `func(item)` будет запущен параллельно, без ожидания завершения предыдущего вызова. Это может быть полезно, если вам не важен порядок выполнения и вы хотите запустить все вызовы `func(item)` одновременно.

---
Когда мы используем `Promise.all()` вместе с `array.map()`, мы создаем массив промисов, каждый из которых представляет асинхронную операцию `func(item)` для каждого элемента `array`.

`Promise.all()` ожидает разрешения всех промисов в массиве. Это означает, что код будет приостановлен, пока все асинхронные операции не завершатся.

Когда все промисы разрешаются, это означает, что все асинхронные операции `func(item)` в цикле `array.map()` завершены.

После этого, код после `await Promise.all()` будет выполнен. В данном случае, это `console.log('Done!')`, которое выводит сообщение "Done!" в консоль.

---
### _Определить анонимную функцию как асинхронную:_

**-> Не сработает корректно**
```
async function processArray(array) {
  array.forEach(async (item) => {
    await func(item);
  })
  console.log('Done!');
}
```

`forEach` не будет дожидаться выполнения завершения задачи. `forEach` — синхронная операция. Она просто запустит задачи и пойдет дальше.  

---
## _Event Loop_

`Event Loop` - цикл событий. Его идея заключается в том, что есть бесконечный цикл, в котором движок языка JavaScript ожидает задачи, выполняет их и снова ожидает появление новых задач.

1) `Call Stack` (`Callback Stack`) - отвечает за выполнение `синхронного` кода.  
2) `Microtask Queue` (`Job Queue` or `Promise Queue`) - отвечает за выполнение `микрозадач` (`промисов`, `try/catch/finally`).
3) `Callback Queue` (`Task Queue` or `Message Queue`) - отвечает за выполнение `колбэков асинхронных операций`, таких как `таймеры` или `events`.  
! Эта очередь начнет выполняться после того, как Call Stack полностью очистится.
Как только `Call Stack` будет пуст, элемент из `Callback Queue` переместиться в `stack` и там выполниться.

### _Приоритет выполнения_

- `мАкрозадачи` - основная `макрозадача` - движение от первой строчки кода к последней (выполнение `скрипта`)
Если движок достиг последней строчки кода, выполнив все `макрозадачи`, 
То переходит к очереди `микрозадач`:

- `мИкрозадачи` - `промисы`, `try/catch/finally`
Если в `микрозадачах` что-то есть, то добавляет в `Call Stack` и выполняет. 
Если нет или закончились, то проверяет:

- `Callback Queue` -  `таймеры`, `events`.  
Если там есть задачи, то так же удаляет ее из очереди, добавляет в Callback Stack, вызывает и удаляет как отработанную 
